#!/usr/bin/env fish
# install fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > /tmp/install
fish /tmp/install --path=~/.local/share/omf --config=/tmp/omf/.config/omf --yes
omf install https://github.com/catppuccin/fish
fish_config theme save "Catppuccin Mocha"

